TARGETS = dj-glove btpingpong

ARDUINO_INC_PATH  = /usr/share/arduino/hardware/arduino
ARDUINO_CORE_PATH = $(ARDUINO_INC_PATH)/cores/arduino/
ARDUINO_VAR_PATH  = $(ARDUINO_INC_PATH)/variants/standard

